---
- name: dns | Setting DNS Servers
  set_fact:
    vsphere_dns_nameservers: "{{ vsphere_dns_servers|join(',') }}"
  when: >
        groups['vsphere_powerdns_vms'] is not defined and
        (vsphere_dns_servers is defined and
          vsphere_dns_servers != [])

- name: dns | Setting DNS Servers (PowerDNS)
  set_fact:
    vsphere_dns_nameservers: "{% for item in groups['vsphere_powerdns_vms'] %}{{ hostvars[item]['ansible_host'] }}{% if not loop.last %},{% endif %}{% endfor %}"
  when: >
        groups['vsphere_powerdns_vms'] is defined

- name: dns | Configuring DNS
  vmware_dns_config:
    hostname: "{{ hostvars[item]['ansible_host'] }}"
    username: "{{ vsphere_user_info['username'] }}"
    password: "{{ vsphere_user_info['password'] }}"
    change_hostname_to: "{{ hostvars[item]['inventory_hostname_short'] }}"
    domainname: "{{ pri_domain_name }}"
    dns_servers: "{{ vsphere_dns_nameservers }}"
    validate_certs: "{{ vsphere_validate_certs }}"
  delegate_to: localhost
  with_items: "{{ groups[vsphere_management_hosts_group] }}"
  when: vsphere_dns_nameservers is defined
