---
# tasks file for ansible-vsphere-management

- include: set_facts.yml
  tags:
    - vsphere_bootstrap_vms
    - vsphere_ddi_vms
    - vsphere_dhcp_vms
    - vsphere_dns
    - vsphere_dnsdist_vms
    - vsphere_lb
    - vsphere_lb_vms
    - vsphere_management
    - vsphere_network
    - vsphere_samba_vms

- include: invalid_certs.yml
  tags:
    - vsphere_management

- include: creds.yml
  tags:
    - vsphere_bootstrap_vms
    - vsphere_ddi_vms
    - vsphere_dhcp_vms
    - vsphere_dns
    - vsphere_dnsdist_vms
    - vsphere_lb
    - vsphere_lb_vms
    - vsphere_management
    - vsphere_network
    - vsphere_samba_vms

- include: network.yml
  tags:
    - vsphere_management
    - vsphere_network

- include: ssh.yml
  tags:
    - vsphere_management

- include: ntp.yml
  tags:
    - vsphere_management

- include: iscsi.yml
  tags:
    - vsphere_iscsi
    - vsphere_management

- include: datastores.yml
  tags:
    - vsphere_management

- include: maintenance_mode.yml
  tags:
    - vsphere_maintenance_mode
    - vsphere_management
    - vsphere_updates

- include: updates.yml
  tags:
    - vsphere_management
    - vsphere_updates

- include: template_vm.yml
  when: >
        vsphere_template_vm is defined and
        (vsphere_template_vm['deploy'] is defined and
        vsphere_template_vm['deploy'])
  tags:
    - vsphere_management

- include: bootstrap_vms.yml
  tags:
    - vsphere_bootstrap_vms
  when: vsphere_bootstrap_vms is defined

- include: ddi_vms.yml
  tags:
    - vsphere_ddi_vms
    - vsphere_dhcp_vms
  when: vsphere_ddi_vms is defined

- include: dnsdist_vms.yml
  tags:
    - vsphere_dnsdist_vms
  when: vsphere_dnsdist_vms is defined

- include: dhcp_vms.yml
  tags:
    - vsphere_ddi_vms
    - vsphere_dhcp_vms
  when: vsphere_ddi_vms is defined

- include: lb_vms.yml
  tags:
    - vsphere_lb
    - vsphere_lb_vms
  when: vsphere_lb_vms is defined

- include: samba_vms.yml
  tags:
    - vsphere_samba_vms
  when: >
        vsphere_samba_vms is defined and
        vsphere_samba_domain

- include: dns.yml
  tags:
    - vsphere_dns
