---
- name: maintenance_mode |
  win_shell: |
    $vmHost="{{ vsphere_management_host_ip }}"
    Connect-VIServer -Server $vmHost
    $MaintenanceMode=$(Get-VMHost | Select-Object -ExpandProperty State)
    {%   if vsphere_maintenance_mode %}
    if ($MaintenanceMode -ne 'Maintenance') {
      Set-VMHost -State 'Maintenance' -Confirm:$false
    }
    {%   elif not hostvars[item]['vsphere_maintenance_mode'] %}
    if ($MaintenanceMode -ne 'Connected') {
      Set-VMHost -State 'Connected' -Confirm:$false
    }
    {%   endif %}
    Disconnect-VIServer * -Confirm:$false
  with_items: "{{ groups[vsphere_management_hosts_group] }}"
  when: >
        hostvars[item]['vsphere_maintenance_mode'] is defined
