---
vsphere_vswitches:
  - name: vSwitch0
    load_balancing_policy: LoadBalanceSrcId
    active_nics:
      - vmnic0
      - vmnic1
    standby_nics: []
    unused_nics: []
    portgroups:
      - name: Management Network
        inherit_failover_order: true
        vlan_id: 101
    # vmkernel_ports:
    #   - name: vmk0
    #     enable_ft: false
    #     enable_mgmt: true
    #     enable_vmotion: false
    #     enable_vsan: false
    #     ip_address: '{{ ansible_host }}'
    #     portgroup_name: Management Network
    #     subnet_mask: 255.255.255.0
    #     vland_id: 101
    #     vswitch_name: vSwitch0
  - name: vSwitch1
    active_nics:
      - vmnic2
      - vmnic3
      - vmnic4
      - vmnic5
    standby_nics: []
    unused_nics: []
    portgroups:
      - name: VSS-VLAN-101
        inherit_failover_order: true
        vlan_id: 101
      - name: VSS-VLAN-102
        inherit_failover_order: true
        vlan_id: 102
      - name: VSS-VLAN-201
        inherit_failover_order: true
        vlan_id: 201
