---
vsphere_lb_vms_inventory_file: ../inventory/vsphere_lb_vms.inv

vsphere_lb_vms:
  - vm_name: lb_00
    cpus: 1
    deploy: true
    datastore: Datastore_1
    gateway: 10.0.102.1
    ip: 10.0.102.20
    memory_mb: 1024
    netmask: 255.255.255.0
    netmask_cidr: 24
    network_name: VSS-VLAN-102
    vapp_source_path: C:\vagrant\vApps\ubuntu_16.04_template.ovf
  - vm_name: lb_01
    cpus: 1
    deploy: true
    datastore: Datastore_1
    gateway: 10.0.102.1
    ip: 10.0.102.21
    memory_mb: 1024
    netmask: 255.255.255.0
    netmask_cidr: 24
    network_name: VSS-VLAN-102
    vapp_source_path: C:\vagrant\vApps\ubuntu_16.04_template.ovf
