---
# galera_cluster_bind_address: 0.0.0.0
galera_cluster_bind_interface: ens160
galera_cluster_name: vsphere_powerdns
galera_cluster_nodes_group: vsphere_powerdns_vms
mariadb_pri_domain_name: '{{ pri_domain_name }}'
